#%RAML 1.0 DataType
description: Defines standard system audit fields available for most types
properties:
  createdOn: datetime
  createdBy: string
  updatedOn: datetime
  updatedBy: string
  isDeleted: boolean
example:
  createdOn: 2021-01-21T21:21:21Z
  createdBy: "0054x000002IpBlAAK"
  updatedOn: 2021-01-21T21:21:21Z
  updatedBy: "0054x000002xBGGAA2"
  isDeleted: false
