#%RAML 1.0 DataType
properties:
  street1?:
    type: string | nil
  street2?:
    type: string | nil  
  city?:
    type: string | nil
  state?:
    type: string | nil  
  postalCode?:
    type: string | nil
  countryCode?:
    type: string | nil 